// web/src/components/ui/button.tsx
import type { ButtonHTMLAttributes } from 'react';

import { cx } from '../../lib/cx.js';

type Variant = 'primary' | 'secondary' | 'ghost' | 'danger';
type Size = 'sm' | 'md';

const variants: Record<Variant, string> = {
  primary: 'bg-primary text-primary-ink hover:bg-primary-hover',
  secondary: 'bg-fill text-ink hover:bg-selected',
  ghost: 'text-ink-2 hover:bg-fill hover:text-ink',
  danger: 'bg-danger text-primary-ink hover:opacity-90',
};

const sizes: Record<Size, string> = {
  sm: 'h-7 rounded-md px-2.5 text-xs',
  md: 'h-9 rounded-lg px-3.5 text-sm',
};

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant;
  size?: Size;
}

export function Button({
  variant = 'primary',
  size = 'md',
  className,
  type = 'button',
  ...rest
}: ButtonProps) {
  return (
    <button
      type={type}
      className={cx(
        'inline-flex items-center justify-center gap-1.5 font-medium transition-colors',
        'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent',
        'disabled:pointer-events-none disabled:opacity-50',
        variants[variant],
        sizes[size],
        className,
      )}
      {...rest}
    />
  );
}

// src/components/Button/Button.svelte
<script lang="ts">
	import Icon from '../Icon/Icon.svelte';
	import type { IconName } from '../Icon/Icons/types';

	export let title: string = '';
	export let onClick = () => {};
	export let icon: IconName | undefined = undefined;
	export let mode: 'default' | 'primary' | 'danger' = 'default';

	const className = [
		'group inline-flex items-center rounded-md border  px-4 py-2 text-sm font-medium  shadow-sm  focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2'
	];
	let iconColor = '';

	if (mode === 'default') {
		className.push('border-gray-300 bg-white text-gray-700 hover:bg-gray-50');
	}
	if (mode === 'danger') {
		className.push('border-red-500 bg-white-500 text-red-500 hover:bg-red-600 hover:text-white');
		iconColor = 'text-red-500 group-hover:text-white';
	}
	if (mode === 'primary') {
		className.push('border-indigo-500 bg-indigo-500 text-white hover:bg-indigo-600');
		iconColor = 'text-indigo-500 group-hover:text-white';
	}
</script>

<button type="button" class={className.join(' ')} on:click={onClick}>
	{#if icon}
		<span class={title ? 'mr-2' : ''}>
			<Icon name={icon} color={iconColor} />
		</span>
	{/if}
	{#if title != ''}
		{title}
	{/if}
	<slot />
</button>
